name: CI

on:
  push:
    branches:
    - master
    - main
    paths:
      - "docker/*"
      - ".github/workflows/main.yml"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u holmesian -p ${{ secrets.DOCKER_HUB_PWD }}

      - name: get golang version 1
        run: |
          export VERSION=$(cat .golang_version | awk -F',' '{print $1}' | sed 's/go1/go-1/')
          echo ::set-output name=value::$VERSION
          DOTS=$(echo -n $VERSION | awk -F"." '{print NF-1}')
          if [ "$DOTS" == "1" ]; then
            echo ::set-output name=wildcard::$VERSION.x
          else
            echo ::set-output name=wildcard::$(echo -n $VERSION | sed 's/\.[^.]*$/.x/')
          fi
        id: golang_version_1
      - name: get golang version 2
        run: |
          export VERSION=$(cat .golang_version | awk -F',' '{print $2}' | sed 's/go1/go-1/')
          echo ::set-output name=value::$VERSION
          DOTS=$(echo -n $VERSION | awk -F"." '{print NF-1}')
          if [ "$DOTS" == "1" ]; then
            echo ::set-output name=wildcard::$VERSION.x
          else
            echo ::set-output name=wildcard::$(echo -n $VERSION | sed 's/\.[^.]*$/.x/')
          fi
        id: golang_version_2

      - name: build Docker base
        run: |
          docker pull holmesian/xgo:base
          docker build --cache-from=holmesian/xgo:base -t holmesian/xgo:base ./docker/base
          docker push holmesian/xgo:base
      - name: build golang ${{ steps.golang_version_1.outputs.value }} image
        uses: docker/build-push-action@v2
        with:
          context: docker/${{ steps.golang_version_1.outputs.value }}/
          tags: holmesian/xgo:${{ steps.golang_version_1.outputs.value }},holmesian/xgo:${{ steps.golang_version_1.outputs.wildcard }}
          push: true
          file: docker/${{ steps.golang_version_1.outputs.value }}/Dockerfile
      - name: build golang ${{ steps.golang_version_2.outputs.value }} image
        uses: docker/build-push-action@v2
        with:
          context: docker/${{ steps.golang_version_2.outputs.value }}/
          tags: holmesian/xgo:${{ steps.golang_version_2.outputs.value }},holmesian/xgo:${{ steps.golang_version_2.outputs.wildcard }}
          push: true
          file: docker/${{ steps.golang_version_2.outputs.value }}/Dockerfile
      - name: build latest image
        uses: docker/build-push-action@v2
        with:
          context: docker/go-latest/
          tags: holmesian/xgo:latest
          push: true
          file: docker/go-latest/Dockerfile
